### ISSUE TITLE
建造者模式里的itemsName哪里来的？

### ISSUE THREAD

**Issue by LaughSun0513** [zy445566/design-pattern-in-javascript#1]
建造者模式里的itemsName哪里来的？

**Comment by zy445566** [comment]
写文章的时候，因为边写代码边写文章，有的时候代码没有及时同步，后面就忘记了。
但其实每个目录下面都有对应的代码，像建造者的代码是 https://github.com/zy445566/design-pattern-in-javascript/blob/master/design-pattern/builder-pattern/index.js 
最近两天事情比较多，看看明天下午同步一下。

题外话，这个仓库是有一年多前为了学习设计模式写的，每段时间都有每段时间不同的变化，现在我觉得在js中强套设计模式可能会有点奇怪，因为很多具体的设计模式是解决一些强类型不好完成的事情，但是思想还是通用的，比如组合，责任单一等等。后来我发现在写js结合函数式编程思想帮助会大一些，比如副作用识别和无状态编程。
所以这也是我没有把这个仓库放在首页的原因

**Comment by LaughSun0513** [comment]
> 写文章的时候，因为边写代码边写文章，有的时候代码没有及时同步，后面就忘记了。
> 但其实每个目录下面都有对应的代码，像建造者的代码是 https://github.com/zy445566/design-pattern-in-javascript/blob/master/design-pattern/builder-pattern/index.js
> 最近两天事情比较多，看看明天下午同步一下。
> 
> 题外话，这个仓库是有一年多前为了学习设计模式写的，每段时间都有每段时间不同的变化，现在我觉得在js中强套设计模式可能会有点奇怪，因为很多具体的设计模式是解决一些强类型不好完成的事情，但是思想还是通用的，比如组合，责任单一等等。后来我发现在写js结合函数式编程思想帮助会大一些，比如副作用识别和无状态编程。
> 所以这也是我没有把这个仓库放在首页的原因

感谢回复啊，最近在看关于设计模式的书，刚好搜到了您的代码，觉得您写的例子比较通俗易懂，书中还是用的es5的思路在写，有时候看书不明白的地方就来看看您的这个例子，但是看到建造者模式的时候，就发现了错误，不过赞同您说的，生搬硬套不好，但是很多时候敲代码还是发现写if-else的代码没有美观性，函数式编程和设计模式的思想还是很必要的，代码组合拼装的思路肯定比过程式代码要可维护，舒服很多，欢迎大佬分享编程过程中的心得

**Comment by zy445566** [comment]
> 感谢回复啊，最近在看关于设计模式的书，刚好搜到了您的代码，觉得您写的例子比较通俗易懂，书中还是用的es5的思路在写，有时候看书不明白的地方就来看看您的这个例子，但是看到建造者模式的时候，就发现了错误，不过赞同您说的，生搬硬套不好，但是很多时候敲代码还是发现写if-else的代码没有美观性，函数式编程和设计模式的思想还是很必要的，代码组合拼装的思路肯定比过程式代码要可维护，舒服很多，欢迎大佬分享编程过程中的心得

也感谢你发现问题，问题已经修复，那么问题我关闭了
